import Head from "next/head";
import { Space_Grotesk } from "next/font/google";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import BrandLogos from "@/components/BrandLogos";
import Services from "@/components/Services";
import CaseStudies from "@/components/CaseStudies";
import WorkingProcess from "@/components/WorkingProcess";
import Team from "@/components/Team";
import Testimonials from "@/components/Testimonials";

const sg = Space_Grotesk({ subsets: ["latin"], weight: ["300", "500"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={sg.className}>
        <Header />
        <HeroSection />
        <BrandLogos />
        <Services />
        <CaseStudies />
        <WorkingProcess />
        <Team />
        <Testimonials />
      </main>
    </>
  );
}
